(define-module (chapter-2 exercise-36)
  #:use-module (chapter-2 exercise-33)
  #:re-export  (accumulate)
  #:export     (accumulate-n))

(define (accumulate-n op init seqs)
  (if (null? (car seqs))
      '()
      (cons (accumulate op init (map car seqs))
	    (accumulate-n op init (map cdr seqs)))))
